db.imps.insert({"cardName": "Darth Vader", "imageFile": "images/imps/advanced_darthvader.jpg"})
db.imps.insert({"cardName": "Maarek Stele", "imageFile": "images/imps/advanced_maarekstele.jpg"})
db.imps.insert({"cardName": "Stormstaffel", "imageFile": "images/imps/advanced_stormstaffel.jpg"})
db.imps.insert({"cardName": "Tornadostaffel", "imageFile": "images/imps/advanced_tornadostaffel.jpg"})
db.imps.insert({"cardName": "Captain Jonus", "imageFile": "images/imps/bomber_captainjonus.jpg"})
db.imps.insert({"cardName": "Gammastaffel", "imageFile": "images/imps/bomber_gammastaffel.jpg"})
db.imps.insert({"cardName": "Major Rhymer", "imageFile": "images/imps/bomber_majorrhymer.jpg"})
db.imps.insert({"cardName": "Scimitarstaffel", "imageFile": "images/imps/bomber_scimitarstaffel.jpg"})
db.imps.insert({"cardName": "Colonel Vessery", "imageFile": "images/imps/defender_colonelvessery.jpg"})
db.imps.insert({"cardName": "Deltastaffel", "imageFile": "images/imps/defender_deltastaffel.jpg"})
db.imps.insert({"cardName": "Onystaffel", "imageFile": "images/imps/defender_onyxstaffel.jpg"})
db.imps.insert({"cardName": "Rexler Brath", "imageFile": "images/imps/defender_rexlerbrath.jpg"})
db.imps.insert({"cardName": "Akademiker", "imageFile": "images/imps/fighter_akademiker.jpg"})
db.imps.insert({"cardName": "Backstabber", "imageFile": "images/imps/fighter_backstabber.jpg"})
db.imps.insert({"cardName": "Dark Curse", "imageFile": "images/imps/fighter_darkcurse.jpg"})
db.imps.insert({"cardName": "Geflügelter Gundark", "imageFile": "images/imps/fighter_gefluegeltergundark.jpg"})
db.imps.insert({"cardName": "Kreischläufer", "imageFile": "images/imps/fighter_kreischlaeufer.jpg"})
db.imps.insert({"cardName": "Mauler Mithel", "imageFile": "images/imps/fighter_maulermithel.jpg"})
db.imps.insert({"cardName": "Nachtbestie", "imageFile": "images/imps/fighter_nachtbestie.jpg"})
db.imps.insert({"cardName": "Obsidianstaffel", "imageFile": "images/imps/fighter_obsidianstaffel.jpg"})
db.imps.insert({"cardName": "Schwarzstaffel", "imageFile": "images/imps/fighter_schwarzstaffel.jpg"})
db.imps.insert({"cardName": "Boba Fett", "imageFile": "images/imps/firespray_bobafett.jpg"})
db.imps.insert({"cardName": "Alphastaffel", "imageFile": "images/imps/interceptor_alphastaffel.jpg"})
db.imps.insert({"cardName": "Carnor Jax", "imageFile": "images/imps/interceptor_carnorjax.jpg"})
db.imps.insert({"cardName": "Kir Kanos", "imageFile": "images/imps/interceptor_kirkanos.jpg"})
db.imps.insert({"cardName": "Lieutenant Lorrir", "imageFile": "images/imps/interceptor_lieutenantlorrir.jpg"})
db.imps.insert({"cardName": "Rote Garde", "imageFile": "images/imps/interceptor_rotegarde.jpg"})
db.imps.insert({"cardName": "Saberstaffel", "imageFile": "images/imps/interceptor_saberstaffel.jpg"})
db.imps.insert({"cardName": "Tetran Cowall", "imageFile": "images/imps/interceptor_tetrancowall.jpg"})
db.imps.insert({"cardName": "Echo", "imageFile": "images/imps/phantom_echo.jpg"})
db.imps.insert({"cardName": "Schattenstaffel", "imageFile": "images/imps/phantom_schattenstaffel.jpg"})
db.imps.insert({"cardName": "Sigmastaffel", "imageFile": "images/imps/phantom_sigmastaffel.jpg"})
db.imps.insert({"cardName": "Whisper", "imageFile": "images/imps/phantom_whisper.jpg"})
