db.rebels.insert({"cardName": "Arvel Crynd", "imageFile": "images/rebels/awing_arvelcrynyd.jpg"})
db.rebels.insert({"cardName": "Gemmer Sojan", "imageFile": "images/rebels/awing_gemmersojan.jpg"})
db.rebels.insert({"cardName": "Grün Staffel", "imageFile": "images/rebels/awing_grünstaffel.jpg"})
db.rebels.insert({"cardName": "Jake Farrel", "imageFile": "images/rebels/awing_jakefarrell.jpg"})
db.rebels.insert({"cardName": "A Test Pilot", "imageFile": "images/rebels/awing_testpilot.jpg"})
db.rebels.insert({"cardName": "Tycho Celchu", "imageFile": "images/rebels/awing_tychocelchu.jpg"})
db.rebels.insert({"cardName": "Blau Staffel", "imageFile": "images/rebels/bwing_blaustaffel.jpg"})
db.rebels.insert({"cardName": "Dagger Staffel", "imageFile": "images/rebels/bwing_daggerstaffel.jpg"})
db.rebels.insert({"cardName": "Ibit Sam", "imageFile": "images/rebels/bwing_ibitsam.jpg"})
db.rebels.insert({"cardName": "Nera Dantels", "imageFile": "images/rebels/bwing_neradantels.jpg"})
db.rebels.insert({"cardName": "Ten Numb", "imageFile": "images/rebels/bwing_tennumb.jpg"})
db.rebels.insert({"cardName": "Corran Horn", "imageFile": "images/rebels/ewing_corranhorn.jpg"})
db.rebels.insert({"cardName": "Etahn A Baht", "imageFile": "images/rebels/ewing_etahnabaht.jpg"})
db.rebels.insert({"cardName": "Schurken Staffel", "imageFile": "images/rebels/ewing_schurkenstaffel.jpg"})
db.rebels.insert({"cardName": "Schwarzmond Staffel", "imageFile": "images/rebels/ewing_schwarzmondstaffel.jpg"})
db.rebels.insert({"cardName": "Han Solo", "imageFile": "images/rebels/falke_hansolo.jpg"})
db.rebels.insert({"cardName": "Rebellenagentgent", "imageFile": "images/rebels/hwk_agent.jpg"})
db.rebels.insert({"cardName": "Jan Ors", "imageFile": "images/rebels/hwk_janors.jpg"})
db.rebels.insert({"cardName": "Kyle Katarn", "imageFile": "images/rebels/hwk_kylekatarn.jpg"})
db.rebels.insert({"cardName": "Roark Garnet", "imageFile": "images/rebels/hwk_roarkgarnet.jpg"})
db.rebels.insert({"cardName": "Anfängerpilot", "imageFile": "images/rebels/xwing_anfängerpilot.jpg"})
db.rebels.insert({"cardName": "Biggs Darkleighter", "imageFile": "images/rebels/xwing_biggsdarklighter.jpg"})
db.rebels.insert({"cardName": "Garven Dreis", "imageFile": "images/rebels/xwing_garvendreis.jpg"})
db.rebels.insert({"cardName": "Luke Skywalker", "imageFile": "images/rebels/xwing_lukeskywalker.jpg"})
db.rebels.insert({"cardName": "Rotstaffel", "imageFile": "images/rebels/xwing_rotstaffel.jpg"})
db.rebels.insert({"cardName": "Wedge Antilles", "imageFile": "images/rebels/xwing_wedgeantilles.jpg"})
db.rebels.insert({"cardName": "Chewbacca", "imageFile": "images/rebels/yt1300_chewbacca.jpg"})
db.rebels.insert({"cardName": "Lando Calrissian", "imageFile": "images/rebels/yt1300_landocalrissian.jpg"})
db.rebels.insert({"cardName": "Out Rim Schmuggler", "imageFile": "images/rebels/yt1300_schmuggler.jpg"})
db.rebels.insert({"cardName": "Dash Rendar", "imageFile": "images/rebels/yt2400_dashrendar.jpg"})
db.rebels.insert({"cardName": "Eaden Vrill", "imageFile": "images/rebels/yt2400_eadenvrill.jpg"})
db.rebels.insert({"cardName": "Grenzgänger", "imageFile": "images/rebels/yt2400_grenzgänger.jpg"})
db.rebels.insert({"cardName": "Leebo", "imageFile": "images/rebels/yt2400_leebo.jpg"})
db.rebels.insert({"cardName": "Dutch Vander", "imageFile": "images/rebels/ywing_dutchvander.jpg"})
db.rebels.insert({"cardName": "Goldstaffel", "imageFile": "images/rebels/ywing_goldstaffel.jpg"})
db.rebels.insert({"cardName": "Graustaffel", "imageFile": "images/rebels/ywing_graustaffel.jpg"})
db.rebels.insert({"cardName": "Horton Salm", "imageFile": "images/rebels/ywing_hortonsalm.jpg"})
db.rebels.insert({"cardName": "Airencracken", "imageFile": "images/rebels/z95_airencracken.jpg"})
db.rebels.insert({"cardName": "Banditstaffel", "imageFile": "images/rebels/z95_banditstaffel.jpg"})
db.rebels.insert({"cardName": "Lieutenant Blount", "imageFile": "images/rebels/z95_lieutenantblount.jpg"})
db.rebels.insert({"cardName": "Talastaffel", "imageFile": "images/rebels/z95_talastaffel.jpg"})